main.adb:9:04: error: "Constraint_Error" would have been raised at run time
main.adb:9:04: error: error in inlined body at line 5
main.adb:9:04: error: value not in range of type "Standard.Integer"
main2.adb:8:28: error: "Constraint_Error" would have been raised at run time
main2.adb:8:28: error: error in inlined body at line 5
main2.adb:8:28: error: value not in range of type "Standard.Integer"
main3.adb:7:04: error: "Constraint_Error" would have been raised at run time
main3.adb:7:04: error: error in inlined body at line 4
main3.adb:7:04: error: value not in range of type universal integer
neg.adb:10:04: error: "Constraint_Error" would have been raised at run time
neg.adb:10:04: error: "Constraint_Error" would have been raised at run time
neg.adb:10:04: error: error in inlined body at line 5
neg.adb:10:04: error: error in inlined body at line 6
neg.adb:10:04: error: value not in range of type "Standard.Integer"
neg.adb:10:04: error: value not in range of type "Standard.Integer"
gnatprove: error during generation of Global contracts
